apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-app2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app2/
    repoURL: https://github.com/FrenkyFix1987/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true